=head1 NAME

camera-calib - GUI for calibrating a monocular camera using a checker-board

=head1 SYNOPSIS

camera-calib

=head1 DESCRIPTION

B<camera-calib-gui> is a graphical application which allows the user to select a sequence
of images where a checkerboad (calibration pattern) appears, then it computes the intrinsic
and distortion parameters of the camera, using the OpenCV implementation of Zhang's algorithm.

The sequence of images can be grabbed directly from a webcam, firewire camera or any 
other video source.


=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Applications

=head1 AUTHORS

B<camera-calib> is part of the Mobile Robot Programming Toolkit (MRPT), and was originally 
written by the MAPIR laboratory (University of Malaga).

This manual page was written by Jose Luis Blanco <joseluisblancoc@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be 
found in `/usr/share/common-licenses/BSD'.

=cut

