=head1 NAME

kinect-stereo-calib - Calibration utility for the Microsoft Kinect sensor

=head1 SYNOPSIS

kinect-stereo-calib

=head1 DESCRIPTION

B<kinect-stereo-calib> is designed to allow an easy calibration of the 
camera intrinsic and extrinsic parameters required for an accurate
reconstruction of colored 3D point clouds with this sensor.
Calibration will require a printed checkerboard as those used
in common camera calibration. 

It can be also used to calibrate any arbitrary stereo camera, provided
stereo images of a checkerboard are already saved to disk.


=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Kinect_and_MRPT

=head1 AUTHORS

B<kinect-stereo-calib> is part of the Mobile Robot Programming Toolkit (MRPT), 
and was originally written by Jose Luis Blanco (University of Malaga).

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be 
found in `/usr/share/common-licenses/BSD'.

=cut
