=head1 NAME

mono-slam - Monocular Visual Simultaneous Localization and Mapping (SLAM)

=head1 SYNOPSIS

mono-slam

=head1 DESCRIPTION

B<mono-slam> is a GUI application intended to demonstrate the usage of the 
Monocular SLAM classes within MRPT. The GUI includes an embedded camera 
calibration routine.


=head1 BUGS

Please report bugs at http://www.mrpt.org/project/issues/MRPT

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Applications

=head1 AUTHORS

B<mono-slam> is part of the Mobile Robot Programming Toolkit (MRPT), and was originally 
written by the MAPIR laboratory (University of Malaga).

This manual page was written by Jose Luis Blanco <joseluisblancoc@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3, or (at your option) any
later version.

On Debian GNU/Linux systems, the complete text of the GNU General
Public License can be found in `/usr/share/common-licenses/GPL'.

=cut

