=head1 NAME

mrpt-performance - Complete performance test for MRPT

=head1 SYNOPSIS

mrpt-performance

=head1 DESCRIPTION

B<mrpt-performance> is a command-line tool for performing a complete test of 
performance (in execution time) of many different modules of MRPT. The results
are dumped as an HTML document.

=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Applications

=head1 AUTHORS

B<mrpt-performance> is part of the Mobile Robot Programming Toolkit (MRPT), 
and was originally written by the MAPIR laboratory (University of Malaga).

This manual page was written by Jose Luis Blanco <joseluisblancoc@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be 
found in `/usr/share/common-licenses/BSD'.

=cut

