=head1 NAME

prrt-navigator-demo - Mobile robot navigation simulator 

=head1 SYNOPSIS

prrt-navigator-demo

=head1 DESCRIPTION

B<prrt-navigator-demo> is a GUI program that allows experimenting with a 
new robot navigation algorithm based on Rapidly-exploring Random Tree (RTT) 
exploration using Parameterized Trajectory Generators (PTGs). 

Refer to the source code and related papers for more information about the 
method itself.

=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Applications

=head1 AUTHORS

B<prrt-navigator-demo> is part of the Mobile Robot Programming Toolkit (MRPT), and was originally 
written by the MAPIR laboratory (University of Malaga).

This manual page was written by Jose Luis Blanco <joseluisblancoc@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be 
found in `/usr/share/common-licenses/BSD'.

=cut

