=head1 NAME

ReactiveNavigationDemo - GUI demo of robot reactive navigation

=head1 SYNOPSIS

ReactiveNavigationDemo

=head1 DESCRIPTION

A program to demonstrate the usage of the mrpt-nav library. It allow the 
user to set an arbitrary target and then simulate the robot actions to try to reach
the target.

The movements take into account the arbitrary shape of the robot, and a set of
kinematically-constrained trajectories.

=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Applications

=head1 AUTHORS

B<ReactiveNavigationDemo> is part of the Mobile Robot Programming Toolkit (MRPT), and was originally
written by the MAPIR laboratory (University of Malaga).

This manual page was written by Jose Luis Blanco <joseluisblancoc@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be
found in `/usr/share/common-licenses/BSD'.

=cut
