=head1 NAME

robotic-arm-kinematics - GUI for editing and visualizing Denavit-Hartenberg parameters

=head1 SYNOPSIS

robotic-arm-kinematics

=head1 DESCRIPTION

B<robotic-arm-kinematics> is a graphical application with both practical and 
didactic intentions: it can be used to teach and learn the usage of 
Denavit-Hartenberg (DH) parameters to define the kinematic chain of robotic 
manipulators. But it can be also used to define real kinematic chains for 
a subsequent usage within C++ programs.


=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Applications

=head1 AUTHORS

B<robotic-arm-kinematics> is part of the Mobile Robot Programming Toolkit (MRPT), 
and was originally written by the MAPIR laboratory (University of Malaga).

This manual page was written by Jose Luis Blanco <joseluisblancoc@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be 
found in `/usr/share/common-licenses/BSD'.

=cut

