=head1 NAME

simul-beacons - Robot dataset simulator

=head1 SYNOPSIS

simul-beacons I<config_file.ini>

=head1 DESCRIPTION

B<simul-beacons> is a command-line application which generates a synthetic rawlog of a simulated robot 
as it follows a predefined path and observes a set of beacons (through range-only measurements).

=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application wiki page at http://www.mrpt.org/Applications

=head1 AUTHORS

B<simul-beacons> is part of the Mobile Robot Programming Toolkit (MRPT), and was originally 
written by the MAPIR laboratory (University of Malaga).

This manual page was written by Jose Luis Blanco <joseluisblancoc@gmail.com>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be 
found in `/usr/share/common-licenses/BSD'.

=cut

