=head1 NAME

yaml2ini - Converts YAML files into INI-like configuration files.

=head1 SYNOPSIS

yaml2ini I<in.yml>

=head1 DESCRIPTION

B<yaml2ini> is a command-line application which processes a YAML file and prints
to the console the INI-like configuration file.

=head1 BUGS

Please report bugs at https://github.com/MRPT/mrpt/issues

=head1 SEE ALSO

The application list and their documentation: https://docs.mrpt.org/reference/latest/applications.html

=head1 AUTHORS

B<yaml2ini> is part of the Mobile Robot Programming Toolkit (MRPT).

This manual page was written by Jose Luis Blanco <jlblanco@ual.es>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the BSD License.

On Debian GNU/Linux systems, the complete text of the BSD License can be 
found in `/usr/share/common-licenses/BSD'.

=cut

