if(UNIX)
	execute_process(COMMAND uname -m
		OUTPUT_VARIABLE CMAKE_MRPT_ARCH
		OUTPUT_STRIP_TRAILING_WHITESPACE)
	execute_process(COMMAND uname -s
		OUTPUT_VARIABLE CMAKE_MRPT_KERNEL
		OUTPUT_STRIP_TRAILING_WHITESPACE)
	if ($ENV{VERBOSE})
		message(STATUS "Kernel name (uname -s): ${CMAKE_MRPT_KERNEL}")
	endif()
endif()

# Detect if we are in i386 / amd64:
if ("${CMAKE_MRPT_ARCH}" STREQUAL "x86_64" OR "${CMAKE_MRPT_ARCH}" STREQUAL "i686")
	set(MRPT_ARCH_INTEL_COMPATIBLE 1)
else()
	set(MRPT_ARCH_INTEL_COMPATIBLE 0)
endif()
