# Define the helper variables:
#  MRPT_COMPILER_IS_CLANG
#  MRPT_COMPILER_IS_GCC
#  MRPT_COMPILER_IS_GCC_OR_CLANG

set(MRPT_COMPILER_IS_CLANG 0)
if (${CMAKE_CXX_COMPILER_ID}  STREQUAL "Clang")
	set(MRPT_COMPILER_IS_CLANG 1)
endif()
set(MRPT_COMPILER_IS_GCC ${CMAKE_COMPILER_IS_GNUCXX})
if (MRPT_COMPILER_IS_GCC OR MRPT_COMPILER_IS_CLANG)
	set(MRPT_COMPILER_IS_GCC_OR_CLANG 1)
else()
	set(MRPT_COMPILER_IS_GCC_OR_CLANG 0)
endif()
