
SET(CMAKE_MRPT_HAS_JSONCPP 0)
SET(CMAKE_MRPT_HAS_JSONCPP_SYSTEM 0)

OPTION(DISABLE_JSONCPP "Forces NOT using JSONCPP, even if it could be found by CMake" "OFF")
MARK_AS_ADVANCED(DISABLE_JSONCPP)

IF(NOT DISABLE_JSONCPP)
	find_package(jsoncpp QUIET)
	if(jsoncpp_FOUND)
		# cmake imported target: "jsoncpp_lib"
		SET(CMAKE_MRPT_HAS_JSONCPP 1)
		SET(CMAKE_MRPT_HAS_JSONCPP_SYSTEM 1)
	endif()
ENDIF()
