from __future__ import annotations
import mrpt.img
import mrpt.math
import mrpt.poses
import numpy
import typing
from . import stock_objects
__all__: list[str] = ['AssimpLoadFlags', 'BACK', 'BOTTOM', 'CAnimatedAssimpModel', 'CArrow', 'CAssimpModel', 'CAxis', 'CBox', 'CCamera', 'CColorBar', 'CCylinder', 'CDisk', 'CEllipsoid2D', 'CEllipsoid3D', 'CEllipsoidInverseDepth2D', 'CEllipsoidInverseDepth3D', 'CEllipsoidRangeBearing2D', 'CFrustum', 'CGridPlaneXY', 'CGridPlaneXZ', 'CMesh', 'CMesh3D', 'CMeshFast', 'COLOR_FROM_HEIGHT', 'COLOR_FROM_OCCUPANCY', 'COLOR_FROM_RGB_DATA', 'COctoMapVoxels', 'COrbitCameraController', 'CPointCloud', 'CPointCloudColoured', 'CPolyhedron', 'CSetOfLines', 'CSetOfObjects', 'CSetOfTexturedTriangles', 'CSetOfTriangles', 'CSimpleLine', 'CSkyBox', 'CSphere', 'CText', 'CText3D', 'CTexturedPlane', 'CVectorField2D', 'CVectorField3D', 'CVisualObject', 'CubeTextureFace', 'Directional', 'FIXED', 'FRONT', 'FlipUVs', 'IgnoreMaterialColor', 'LEFT', 'OctoMapVisualizationMode', 'Point', 'RIGHT', 'RealTimeFast', 'RealTimeMaxQuality', 'RealTimeQuality', 'Scene', 'Spot', 'TLight', 'TLightType', 'TOP', 'TRANSPARENCY_FROM_OCCUPANCY', 'TRANS_AND_COLOR_FROM_OCCUPANCY', 'TTriangle', 'TTriangleVertex', 'Verbose', 'Viewport', 'posePDF2opengl', 'stock_objects']
class CVisualObject:
    name: str
    visible: bool
    def getColor(self) -> mrpt.img.TColorf:
        ...
    def getPose(self) -> mrpt.math.TPose3D:
        ...
    @typing.overload
    def setColor(self, r: int, g: int, b: int, a: int = 255) -> None:
        ...
    @typing.overload
    def setColor(self, color: mrpt.img.TColorf) -> None:
        """
        Sets the color from a TColorf (float components in [0,1])
        """
    @typing.overload
    def setColor(self, color: mrpt.img.TColor) -> None:
        """
        Sets the color from a TColor (uint8 components)
        """
    @typing.overload
    def setColor(self, r: float, g: float, b: float, a: float = 1.0) -> None:
        """
        Sets the color from float components in [0,1]
        """
    @typing.overload
    def setLocation(self, x: float, y: float, z: float) -> None:
        """
        Changes the position, keeping the orientation
        """
    @typing.overload
    def setLocation(self, p: mrpt.math.TPoint3D) -> None:
        ...
    @typing.overload
    def setPose(self, pose: mrpt.poses.CPose3D) -> None:
        ...
    @typing.overload
    def setPose(self, pose: mrpt.poses.CPose2D) -> None:
        ...
    @typing.overload
    def setScale(self, s: float) -> None:
        """
        Sets the same scale factor in x, y and z
        """
    @typing.overload
    def setScale(self, sx: float, sy: float, sz: float) -> None:
        ...
    @property
    def castShadows(self) -> bool:
        """
        Whether the object casts shadows (if shadows are enabled in the viewport)
        """
    @castShadows.setter
    def castShadows(self, arg1: bool) -> None:
        ...
    @property
    def pose(self) -> mrpt.math.TPose3D:
        ...
    @pose.setter
    def pose(self, arg1: mrpt.poses.CPose3D) -> CVisualObject:
        ...
class CSetOfObjects(CVisualObject):
    def __init__(self) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __lshift__(self, obj):
        ...
    def clear(self) -> None:
        ...
    def insert(self, obj: CVisualObject) -> None:
        ...
class Viewport:
    def __lshift__(self, obj):
        ...
    def clear(self) -> None:
        ...
    def getCamera(self) -> typing.Any:  # unnamed C++ type
        ...
    def insert(self, obj: CVisualObject) -> None:
        ...
    def setCustomBackgroundColor(self, arg0: mrpt.img.TColorf) -> None:
        ...
    def setViewportPosition(self, arg0: float, arg1: float, arg2: float, arg3: float) -> None:
        ...
    @property
    def name(self) -> str:
        ...
class Scene:
    def __init__(self) -> None:
        ...
    def __lshift__(self, obj):
        ...
    def clear(self, createMainViewport: bool = True) -> None:
        """
        Removes all objects (and viewports), then re-creates the main viewport
        """
    def createViewport(self, name: str) -> Viewport:
        ...
    def getViewport(self, name: str = 'main') -> Viewport:
        ...
    def insert(self, arg0: CVisualObject) -> None:
        ...
class CCamera(CVisualObject):
    def __init__(self) -> None:
        ...
    def setAzimuthDegrees(self, arg0: float) -> None:
        ...
    def setElevationDegrees(self, arg0: float) -> None:
        ...
    def setZoomDistance(self, arg0: float) -> None:
        ...
class CPointCloud(CVisualObject):
    def __init__(self) -> None:
        ...
    def clear(self) -> None:
        ...
    def getPointSize(self) -> float:
        ...
    def insertPoint(self, x: float, y: float, z: float) -> None:
        ...
    def setPointSize(self, pointSize: float) -> None:
        """
        Point size, in pixels
        """
    def setPoints(self, arg0: numpy.ndarray) -> None:
        ...
class CAssimpModel(CVisualObject):
    def __init__(self) -> None:
        ...
    def loadScene(self, file_name: str, flags: int = 4116) -> None:
        ...
class AssimpLoadFlags:
    """
    Members:
    
      RealTimeFast
    
      RealTimeQuality
    
      RealTimeMaxQuality
    
      FlipUVs
    
      IgnoreMaterialColor
    
      Verbose
    """
    FlipUVs: typing.ClassVar[AssimpLoadFlags]
    IgnoreMaterialColor: typing.ClassVar[AssimpLoadFlags]
    RealTimeFast: typing.ClassVar[AssimpLoadFlags]
    RealTimeMaxQuality: typing.ClassVar[AssimpLoadFlags]
    RealTimeQuality: typing.ClassVar[AssimpLoadFlags]
    Verbose: typing.ClassVar[AssimpLoadFlags]
    __members__: typing.ClassVar[dict[str, AssimpLoadFlags]]
    def __and__(self, other: typing.Any) -> typing.Any:
        ...
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __ge__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __gt__(self, other: typing.Any) -> bool:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __invert__(self) -> typing.Any:
        ...
    def __le__(self, other: typing.Any) -> bool:
        ...
    def __lt__(self, other: typing.Any) -> bool:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __or__(self, other: typing.Any) -> typing.Any:
        ...
    def __rand__(self, other: typing.Any) -> typing.Any:
        ...
    def __repr__(self) -> str:
        ...
    def __ror__(self, other: typing.Any) -> typing.Any:
        ...
    def __rxor__(self, other: typing.Any) -> typing.Any:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    def __xor__(self, other: typing.Any) -> typing.Any:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CGridPlaneXY(CVisualObject):
    def __init__(self, xmin: float = -10.0, xmax: float = 10.0, ymin: float = -10.0, ymax: float = 10.0, z: float = 0.0, frequency: float = 1.0) -> None:
        ...
    def setGridFrequency(self, arg0: float) -> None:
        ...
    def setPlaneLimits(self, xmin: float, xmax: float, ymin: float, ymax: float) -> None:
        ...
    def setPlaneZcoord(self, arg0: float) -> None:
        ...
class CGridPlaneXZ(CVisualObject):
    def __init__(self, xmin: float = -10.0, xmax: float = 10.0, zmin: float = -10.0, zmax: float = 10.0, y: float = 0.0, frequency: float = 1.0) -> None:
        ...
    def setGridFrequency(self, arg0: float) -> None:
        ...
    def setPlaneLimits(self, xmin: float, xmax: float, zmin: float, zmax: float) -> None:
        ...
    def setPlaneYcoord(self, arg0: float) -> None:
        ...
class CAxis(CVisualObject):
    def __init__(self, xmin: float = -1.0, ymin: float = -1.0, zmin: float = -1.0, xmax: float = 1.0, ymax: float = 1.0, zmax: float = 1.0, frequency: float = 1.0, lineWidth: float = 3.0, marks: bool = True) -> None:
        ...
    def enableTickMarks(self, arg0: bool) -> None:
        ...
    def getFrequency(self) -> float:
        ...
    def getTextScale(self) -> float:
        ...
    def setAxisLimits(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None:
        ...
    def setFrequency(self, arg0: float) -> None:
        ...
    def setTextScale(self, arg0: float) -> None:
        ...
class CBox(CVisualObject):
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, corner1: mrpt.math.TPoint3D, corner2: mrpt.math.TPoint3D, is_wireframe: bool = False, lineWidth: float = 1.0) -> None:
        ...
    def enableBoxBorder(self, arg0: bool) -> None:
        ...
    def getBoxCorners(self) -> tuple:
        ...
    def isWireframe(self) -> bool:
        ...
    def setBoxBorderColor(self, color: mrpt.img.TColor) -> None:
        """
        Color of the box edges, drawn if enableBoxBorder()
        """
    def setBoxCorners(self, arg0: mrpt.math.TPoint3D, arg1: mrpt.math.TPoint3D) -> None:
        ...
    def setWireframe(self, arg0: bool) -> None:
        ...
class CSphere(CVisualObject):
    def __init__(self, radius: float = 1.0, nDivs: int = 20) -> None:
        ...
    def getRadius(self) -> float:
        ...
    def setNumberDivs(self, arg0: int) -> None:
        ...
    def setRadius(self, arg0: float) -> None:
        ...
class CCylinder(CVisualObject):
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, baseRadius: float, topRadius: float, height: float = 1.0, slices: int = 20) -> None:
        ...
    def getHeight(self) -> float:
        ...
    def setHeight(self, arg0: float) -> None:
        ...
    def setRadii(self, arg0: float, arg1: float) -> None:
        ...
    def setRadius(self, arg0: float) -> None:
        ...
class CArrow(CVisualObject):
    def __init__(self) -> None:
        ...
    def setArrowEnds(self, x0: float, y0: float, z0: float, x1: float, y1: float, z1: float) -> None:
        ...
    def setHeadRatio(self, arg0: float) -> None:
        ...
    def setSmallRadius(self, arg0: float) -> None:
        ...
class CText(CVisualObject):
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, text: str) -> None:
        ...
    def getString(self) -> str:
        ...
    def setFont(self, arg0: str, arg1: int) -> None:
        ...
    def setString(self, arg0: str) -> None:
        ...
class CText3D(CVisualObject):
    def __init__(self, text: str = '', fontName: str = 'sans', scale: float = 1.0) -> None:
        ...
    def getString(self) -> str:
        ...
    def setString(self, arg0: str) -> None:
        ...
class CSetOfLines(CVisualObject):
    def __init__(self) -> None:
        ...
    def __len__(self) -> int:
        ...
    @typing.overload
    def appendLine(self, x0: float, y0: float, z0: float, x1: float, y1: float, z1: float) -> None:
        ...
    @typing.overload
    def appendLine(self, arg0: mrpt.math.TSegment3D) -> None:
        ...
    def clear(self) -> None:
        ...
class CSimpleLine(CVisualObject):
    def __init__(self) -> None:
        ...
    def getLineEnd(self) -> mrpt.math.TPoint3Df:
        ...
    def getLineStart(self) -> mrpt.math.TPoint3Df:
        ...
    def setLineCoords(self, x0: float, y0: float, z0: float, x1: float, y1: float, z1: float) -> None:
        ...
class CEllipsoid3D(CVisualObject):
    def __init__(self) -> None:
        ...
    def set3DsegmentsCount(self, arg0: int) -> None:
        ...
    def setCovMatrix(self, arg0: mrpt.math.CMatrixDouble33) -> None:
        ...
    def setQuantiles(self, arg0: float) -> None:
        ...
class CEllipsoid2D(CVisualObject):
    def __init__(self) -> None:
        ...
    def setCovMatrix(self, arg0: mrpt.math.CMatrixDouble22) -> None:
        ...
    def setQuantiles(self, arg0: float) -> None:
        ...
class CPointCloudColoured(CVisualObject):
    def __init__(self) -> None:
        ...
    def __len__(self) -> int:
        ...
    def clear(self) -> None:
        ...
    def getPointSize(self) -> float:
        ...
    def push_back(self, x: float, y: float, z: float, r: float = 1.0, g: float = 1.0, b: float = 1.0, a: float = 1.0) -> None:
        ...
    def setPointSize(self, pointSize: float) -> None:
        """
        Point size, in pixels
        """
    def size(self) -> int:
        ...
class TTriangleVertex:
    def __init__(self) -> None:
        ...
    def setColor(self, color: mrpt.img.TColor) -> None:
        """
        Set vertex color from TColor
        """
class TTriangle:
    vertices: list[TTriangleVertex]
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, p1: mrpt.math.TPoint3Df, p2: mrpt.math.TPoint3Df, p3: mrpt.math.TPoint3Df) -> None:
        ...
    def computeNormals(self) -> None:
        ...
class CDisk(CVisualObject):
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, out_radius: float, in_radius: float, slices: int = 50) -> None:
        ...
    def setDiskRadius(self, out_radius: float, in_radius: float = 0.0) -> None:
        ...
    def setSlicesCount(self, N: int) -> None:
        ...
    @property
    def in_radius(self) -> float:
        ...
    @property
    def out_radius(self) -> float:
        ...
class CFrustum(CVisualObject):
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, near_distance: float, far_distance: float, horz_FOV_degrees: float, vert_FOV_degrees: float, lineWidth: float = 1.0, draw_lines: bool = True, draw_planes: bool = False) -> None:
        ...
    def setHorzFOV(self, fov_degrees: float) -> None:
        ...
    def setNearFarPlanes(self, near: float, far: float) -> None:
        ...
    def setPlaneColor(self, color: mrpt.img.TColor) -> None:
        ...
    def setVertFOV(self, fov_degrees: float) -> None:
        ...
    @property
    def far_plane(self) -> float:
        ...
    @property
    def horz_fov(self) -> float:
        ...
    @property
    def near_plane(self) -> float:
        ...
    @property
    def vert_fov(self) -> float:
        ...
class CSetOfTriangles(CVisualObject):
    def __init__(self) -> None:
        ...
    def clearTriangles(self) -> None:
        ...
    def getTriangle(self, idx: int) -> TTriangle:
        ...
    def getTrianglesCount(self) -> int:
        ...
    def insertTriangle(self, triangle: TTriangle) -> None:
        ...
class CVectorField2D(CVisualObject):
    def __init__(self) -> None:
        ...
    def clear(self) -> None:
        ...
    def setGridCenterAndCellSize(self, cx: float, cy: float, cell_x: float, cell_y: float) -> None:
        ...
    def setGridLimits(self, xmin: float, xmax: float, ymin: float, ymax: float) -> None:
        ...
    def setPointColor(self, R: float, G: float, B: float, A: float = 1.0) -> None:
        ...
    def setVectorField(self, vx: typing.Any, vy: typing.Any) -> None:  # unnamed C++ type
        ...
    def setVectorFieldColor(self, R: float, G: float, B: float, A: float = 1.0) -> None:
        ...
class CVectorField3D(CVisualObject):
    def __init__(self) -> None:
        ...
    def clear(self) -> None:
        ...
    def setMaxSpeedForColor(self, s: float) -> None:
        ...
    def setPointColor(self, R: float, G: float, B: float, A: float = 1.0) -> None:
        ...
    def setPointCoordinates(self, px: typing.Any, py: typing.Any, pz: typing.Any) -> None:  # unnamed C++ type
        ...
    def setVectorField(self, vx: typing.Any, vy: typing.Any, vz: typing.Any) -> None:  # unnamed C++ type
        ...
    def setVectorFieldColor(self, R: float, G: float, B: float, A: float = 1.0) -> None:
        ...
class CMesh(CVisualObject):
    def __init__(self, enable_transparency: bool = False, xMin: float = -1.0, xMax: float = 1.0, yMin: float = -1.0, yMax: float = 1.0) -> None:
        ...
    def enableColorFromZ(self, v: bool) -> None:
        """
        Enable color from Z height using HOT colormap
        """
    def enableTransparency(self, v: bool) -> None:
        ...
    def enableWireFrame(self, v: bool) -> None:
        ...
    def setGridLimits(self, xMin: float, xMax: float, yMin: float, yMax: float) -> None:
        ...
    def setZ(self, Z: numpy.ndarray) -> None:
        """
        Set height matrix (numpy float32 2D array)
        """
class CColorBar(CVisualObject):
    def __init__(self, colormap: int = 0, width: float = 0.2, height: float = 1.0, min_col: float = 0.0, max_col: float = 1.0, min_value: float = 0.0, max_value: float = 1.0, label_format: str = '%7.02f', label_font_size: float = 0.05000000074505806) -> None:
        ...
    def setColorAndValueLimits(self, col_min: float, col_max: float, value_min: float, value_max: float) -> None:
        ...
    def setColormap(self, colormap: int) -> None:
        ...
class CMesh3D(CVisualObject):
    def __init__(self) -> None:
        ...
    def enableFaceNormals(self, v: bool) -> None:
        ...
    def enableShowEdges(self, v: bool) -> None:
        ...
    def enableShowFaces(self, v: bool) -> None:
        ...
    def enableShowVertices(self, v: bool) -> None:
        ...
    def loadMesh(self, vertices: numpy.ndarray, face_vertices: numpy.ndarray, verts_per_face: numpy.ndarray) -> None:
        """
        Load a mesh from numpy arrays: vertices (Nx3 float32), face_vertices (M,) int32, verts_per_face (F,) int32
        """
class CMeshFast(CVisualObject):
    def __init__(self, enable_transparency: bool = False, xMin: float = -1.0, xMax: float = 1.0, yMin: float = -1.0, yMax: float = 1.0) -> None:
        ...
    def enableColorFromZ(self, v: bool, colormap: int = 4) -> None:
        """
        Enable color from Z height (colormap int)
        """
    def enableTransparency(self, v: bool) -> None:
        ...
    def setGridLimits(self, xmin: float, xmax: float, ymin: float, ymax: float) -> None:
        ...
    def setZ(self, Z: numpy.ndarray) -> None:
        """
        Set height matrix (numpy float32 2D array)
        """
class CTexturedPlane(CVisualObject):
    def __init__(self, x_min: float = -1.0, x_max: float = 1.0, y_min: float = -1.0, y_max: float = 1.0) -> None:
        ...
    def enableLighting(self, enable: bool = True) -> None:
        ...
    def getPlaneCorners(self) -> tuple:
        ...
    def setPlaneCorners(self, xMin: float, xMax: float, yMin: float, yMax: float) -> None:
        ...
    def setTextureRepeat(self, repeatX: float, repeatY: float) -> None:
        ...
class CSetOfTexturedTriangles(CVisualObject):
    def __init__(self) -> None:
        ...
    def clearTriangles(self) -> None:
        ...
    def getTriangle(self, idx: int) -> TTriangle:
        ...
    def getTrianglesCount(self) -> int:
        ...
    def insertTriangle(self, triangle: TTriangle) -> None:
        ...
class CPolyhedron(CVisualObject):
    @staticmethod
    def CreateCuboctahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateDodecahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateHexahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateIcosahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateIcosidodecahedron(radius: float, type: bool = True) -> CPolyhedron:
        ...
    @staticmethod
    def CreateOctahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateTetrahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateTruncatedHexahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateTruncatedIcosahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateTruncatedOctahedron(radius: float) -> CPolyhedron:
        ...
    @staticmethod
    def CreateTruncatedTetrahedron(radius: float) -> CPolyhedron:
        ...
class COrbitCameraController:
    azimuth_deg: float
    elevation_deg: float
    roll_deg: float
    zoom: float
    def __init__(self) -> None:
        ...
    def applyTo(self, cam: CCamera) -> None:
        ...
    def onMouseButton(self, x: int, y: int, button: int, down: bool) -> None:
        ...
    def onMouseMove(self, x: int, y: int, buttons: int, modifiers: int) -> None:
        ...
    def onScroll(self, delta: float, modifiers: int) -> None:
        ...
    def setAzimuthDegrees(self, deg: float) -> None:
        ...
    def setCameraPointing(self, x: float, y: float, z: float) -> None:
        ...
    def setElevationDegrees(self, deg: float) -> None:
        ...
    def setFrom(self, cam: CCamera) -> None:
        ...
    def setZoomDistance(self, d: float) -> None:
        ...
class OctoMapVisualizationMode:
    """
    Members:
    
      FIXED : All voxels have the same fixed color
    
      COLOR_FROM_HEIGHT : Color voxels by height
    
      COLOR_FROM_OCCUPANCY : Color by occupancy probability
    
      TRANSPARENCY_FROM_OCCUPANCY : Transparency from occupancy
    
      TRANS_AND_COLOR_FROM_OCCUPANCY : Both transparency and color from occupancy
    
      COLOR_FROM_RGB_DATA : Use per-voxel stored RGB
    """
    COLOR_FROM_HEIGHT: typing.ClassVar[OctoMapVisualizationMode]
    COLOR_FROM_OCCUPANCY: typing.ClassVar[OctoMapVisualizationMode]
    COLOR_FROM_RGB_DATA: typing.ClassVar[OctoMapVisualizationMode]
    FIXED: typing.ClassVar[OctoMapVisualizationMode]
    TRANSPARENCY_FROM_OCCUPANCY: typing.ClassVar[OctoMapVisualizationMode]
    TRANS_AND_COLOR_FROM_OCCUPANCY: typing.ClassVar[OctoMapVisualizationMode]
    __members__: typing.ClassVar[dict[str, OctoMapVisualizationMode]]
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class COctoMapVoxels(CVisualObject):
    def __init__(self) -> None:
        ...
    def clear(self) -> None:
        ...
    def enableCubeTransparency(self, enable: bool) -> None:
        ...
    def enableLights(self, enable: bool) -> None:
        ...
    def getVoxelCount(self, set_index: int) -> int:
        ...
    def getVoxelSetCount(self) -> int:
        ...
    def push_back_Voxel(self, set_index: int, x: float, y: float, z: float, side: float, r: int = 200, g: int = 200, b: int = 200, a: int = 255) -> None:
        ...
    def resizeVoxelSets(self, n: int) -> None:
        ...
    def resizeVoxels(self, set_index: int, n: int) -> None:
        ...
    def setVisualizationMode(self, mode: OctoMapVisualizationMode) -> None:
        ...
    def showGridLines(self, show: bool) -> None:
        ...
    def showVoxels(self, voxel_set: int, show: bool) -> None:
        ...
    def showVoxelsAsPoints(self, enable: bool) -> None:
        ...
class CubeTextureFace:
    """
    Members:
    
      LEFT
    
      RIGHT
    
      TOP
    
      BOTTOM
    
      FRONT
    
      BACK
    """
    BACK: typing.ClassVar[CubeTextureFace]
    BOTTOM: typing.ClassVar[CubeTextureFace]
    FRONT: typing.ClassVar[CubeTextureFace]
    LEFT: typing.ClassVar[CubeTextureFace]
    RIGHT: typing.ClassVar[CubeTextureFace]
    TOP: typing.ClassVar[CubeTextureFace]
    __members__: typing.ClassVar[dict[str, CubeTextureFace]]
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CSkyBox(CVisualObject):
    def __init__(self) -> None:
        ...
    def assignImage(self, face: CubeTextureFace, img: mrpt.img.CImage) -> None:
        ...
class TLightType:
    """
    Members:
    
      Directional
    
      Point
    
      Spot
    """
    Directional: typing.ClassVar[TLightType]
    Point: typing.ClassVar[TLightType]
    Spot: typing.ClassVar[TLightType]
    __members__: typing.ClassVar[dict[str, TLightType]]
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class TLight:
    attenuation_constant: float
    attenuation_linear: float
    attenuation_quadratic: float
    diffuse: float
    direction: mrpt.math.TPoint3Df
    position: mrpt.math.TPoint3Df
    specular: float
    spot_inner_cutoff_deg: float
    spot_outer_cutoff_deg: float
    type: TLightType
    @staticmethod
    def Directional(dir: mrpt.math.TPoint3Df, r: float = 1.0, g: float = 1.0, b: float = 1.0, diffuse: float = 0.800000011920929, specular: float = 0.949999988079071) -> TLight:
        ...
    def __init__(self) -> None:
        ...
class CEllipsoidInverseDepth2D(CVisualObject):
    def __init__(self) -> None:
        ...
    def getQuantiles(self) -> float:
        ...
    def getUnderflowMaxRange(self) -> float:
        ...
    def setCovMatrix(self, arg0: mrpt.math.CMatrixDouble22) -> None:
        ...
    def setQuantiles(self, q: float) -> None:
        ...
    def setUnderflowMaxRange(self, maxRange: float) -> None:
        ...
class CEllipsoidInverseDepth3D(CVisualObject):
    def __init__(self) -> None:
        ...
    def getQuantiles(self) -> float:
        ...
    def getUnderflowMaxRange(self) -> float:
        ...
    def setCovMatrix(self, arg0: mrpt.math.CMatrixDouble33) -> None:
        ...
    def setQuantiles(self, q: float) -> None:
        ...
    def setUnderflowMaxRange(self, maxRange: float) -> None:
        ...
class CEllipsoidRangeBearing2D(CVisualObject):
    def __init__(self) -> None:
        ...
    def getQuantiles(self) -> float:
        ...
    def setCovMatrix(self, arg0: mrpt.math.CMatrixDouble22) -> None:
        ...
    def setQuantiles(self, q: float) -> None:
        ...
class CAnimatedAssimpModel(CAssimpModel):
    def __init__(self) -> None:
        ...
    def getAnimationCount(self) -> int:
        ...
    def getAnimationDuration(self, anim_idx: int = 0) -> float:
        ...
    def getAnimationName(self, anim_idx: int) -> str:
        ...
    def loadScene(self, file_name: str, flags: int = 4116) -> None:
        ...
    def setActiveAnimation(self, anim_name: str) -> None:
        ...
    def setActiveAnimationByIndex(self, idx: int) -> None:
        ...
    def setAnimationTime(self, t_seconds: float) -> None:
        ...
    def setLooping(self, loop: bool) -> None:
        ...
@typing.overload
def posePDF2opengl(pdf: mrpt.poses.CPosePDF) -> CSetOfObjects:
    """
    Returns a 3D representation of a 2D pose PDF (ellipses, particles, ...)
    """
@typing.overload
def posePDF2opengl(pdf: mrpt.poses.CPose3DPDF) -> CSetOfObjects:
    """
    Returns a 3D representation of a 3D pose PDF (ellipsoids, particles, ...)
    """
BACK: CubeTextureFace
BOTTOM: CubeTextureFace
COLOR_FROM_HEIGHT: OctoMapVisualizationMode
COLOR_FROM_OCCUPANCY: OctoMapVisualizationMode
COLOR_FROM_RGB_DATA: OctoMapVisualizationMode
Directional: TLightType
FIXED: OctoMapVisualizationMode
FRONT: CubeTextureFace
FlipUVs: AssimpLoadFlags
IgnoreMaterialColor: AssimpLoadFlags
LEFT: CubeTextureFace
Point: TLightType
RIGHT: CubeTextureFace
RealTimeFast: AssimpLoadFlags
RealTimeMaxQuality: AssimpLoadFlags
RealTimeQuality: AssimpLoadFlags
Spot: TLightType
TOP: CubeTextureFace
TRANSPARENCY_FROM_OCCUPANCY: OctoMapVisualizationMode
TRANS_AND_COLOR_FROM_OCCUPANCY: OctoMapVisualizationMode
Verbose: AssimpLoadFlags
