"""
Pre-built 3D objects
"""
from __future__ import annotations
import mrpt.viz
__all__: list[str] = ['BumblebeeCamera', 'CornerXYSimple', 'CornerXYZ', 'CornerXYZEye', 'CornerXYZSimple', 'Hokuyo_URG', 'Hokuyo_UTM', 'RobotGiraff', 'RobotPioneer', 'RobotRhodon']
def BumblebeeCamera() -> mrpt.viz.CSetOfObjects:
    ...
def CornerXYSimple(scale: float = 1.0, lineWidth: float = 1.0) -> mrpt.viz.CSetOfObjects:
    ...
def CornerXYZ(scale: float = 1.0) -> mrpt.viz.CSetOfObjects:
    ...
def CornerXYZEye() -> mrpt.viz.CSetOfObjects:
    ...
def CornerXYZSimple(scale: float = 1.0, lineWidth: float = 1.0) -> mrpt.viz.CSetOfObjects:
    ...
def Hokuyo_URG() -> mrpt.viz.CSetOfObjects:
    ...
def Hokuyo_UTM() -> mrpt.viz.CSetOfObjects:
    ...
def RobotGiraff() -> mrpt.viz.CSetOfObjects:
    ...
def RobotPioneer() -> mrpt.viz.CSetOfObjects:
    ...
def RobotRhodon() -> mrpt.viz.CSetOfObjects:
    ...
