"""
Python bindings for mrpt::gui — GUI windows for 3D visualization
"""
from __future__ import annotations
import typing
__all__: list[str] = ['CBaseGUIWindow', 'CDisplayWindow3D']
class CBaseGUIWindow:
    def clearKeyHitFlag(self) -> None:
        ...
    def isOpen(self) -> bool:
        ...
    def keyHit(self) -> bool:
        ...
    def waitForKey(self, ignoreControlKeys: bool = True) -> int:
        """
        Waits until a key is pressed in the window. Returns the key code.
        """
class CDisplayWindow3D(CBaseGUIWindow):
    @staticmethod
    def Create(windowCaption: str = '', width: int = 400, height: int = 300) -> CDisplayWindow3D:
        ...
    def __init__(self, windowCaption: str = '', width: int = 400, height: int = 300) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def forceRepaint(self) -> None:
        ...
    def get3DSceneAndLock(self) -> typing.Any:  # unnamed C++ type
        """
        Get locked 3D scene pointer. Call unlockAccess3DScene() when done.
        """
    def getCameraAzimuthDeg(self) -> float:
        ...
    def getCameraElevationDeg(self) -> float:
        ...
    def getCameraPointingToPoint(self) -> tuple:
        ...
    def getCameraZoom(self) -> float:
        ...
    def getFOV(self) -> float:
        ...
    def getRenderingFPS(self) -> float:
        ...
    def grabImagesStart(self, prefix: str = 'video_') -> None:
        ...
    def grabImagesStop(self) -> None:
        ...
    def isCameraProjective(self) -> bool:
        ...
    def repaint(self) -> None:
        ...
    def resize(self, arg0: int, arg1: int) -> None:
        ...
    def setCameraAzimuthDeg(self, arg0: float) -> None:
        ...
    def setCameraElevationDeg(self, arg0: float) -> None:
        ...
    def setCameraPointingToPoint(self, arg0: float, arg1: float, arg2: float) -> None:
        ...
    def setCameraZoom(self, arg0: float) -> None:
        ...
    def setFOV(self, arg0: float) -> None:
        ...
    def setImageView(self, img: typing.Any) -> None:  # unnamed C++ type
        """
        Display a 2D image in this window
        """
    def setMaxRange(self, arg0: float) -> None:
        ...
    def setMinRange(self, arg0: float) -> None:
        ...
    def setPos(self, arg0: int, arg1: int) -> None:
        ...
    def setProjectiveModel(self, arg0: bool) -> None:
        ...
    def setWindowTitle(self, arg0: str) -> None:
        ...
    def unlockAccess3DScene(self) -> None:
        ...
    def updateWindow(self) -> None:
        ...
    def useCameraFromScene(self, arg0: bool) -> None:
        ...
