"""Sphinx extension for the MRPT Python API reference:

- Gathers the .pyi stubs committed in each module
  (modules/mrpt_*/python/mrpt/<name>/) into a single source tree, documented
  by sphinx-autoapi without building or importing MRPT.
- Cross links each Python class with the page of its C++ class (generated by
  doxyrest), in both directions.
"""

import ast
import glob
import os
import re
import shutil

STUBS_TREE = "_python_api_src"


def modules_dir(app):
    return os.path.abspath(os.path.join(app.srcdir, "..", "..", "modules"))


def collect_stubs(app, config):
    dst_root = os.path.join(app.srcdir, STUBS_TREE)
    shutil.rmtree(dst_root, ignore_errors=True)
    mods = modules_dir(app)
    for stub in glob.glob(os.path.join(mods, "mrpt_*", "python", "mrpt", "**", "*.pyi"), recursive=True):
        rel = stub.split(os.sep + "python" + os.sep, 1)[1]
        dst = os.path.join(dst_root, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(stub, dst)


def python_classes(app):
    """Public classes of each Python module: {"poses": ["CPose2D", ...]}."""
    classes = {}
    for init in glob.glob(os.path.join(app.srcdir, STUBS_TREE, "mrpt", "*", "__init__.pyi")):
        mod = os.path.basename(os.path.dirname(init))
        names = []
        for node in ast.parse(open(init, encoding="utf-8").read()).body:
            if isinstance(node, ast.ImportFrom) and node.module and "_bindings" in node.module:
                names += [a.asname or a.name for a in node.names if a.name[:1].isupper()]
        classes[mod] = names
    return classes


def cpp_doc(app, mod, name):
    """Doxyrest page of the C++ class matching a Python class, if any."""
    for kind in ("class", "struct"):
        for ns in ("mrpt_" + mod, "mrpt"):
            doc = "{}_{}_{}".format(kind, ns, name)
            if os.path.isfile(os.path.join(app.srcdir, doc + ".rst")):
                return doc
    return None


def build_maps(app, config):
    app.mrpt_py_to_cpp = {}
    app.mrpt_cpp_to_py = {}
    for mod, names in python_classes(app).items():
        for name in names:
            doc = cpp_doc(app, mod, name)
            if doc:
                app.mrpt_py_to_cpp["mrpt.{}.{}".format(mod, name)] = doc
                app.mrpt_cpp_to_py[doc] = "mrpt.{}.{}".format(mod, name)


def add_links(app, docname, source):
    text = source[0]
    if docname in app.mrpt_cpp_to_py:
        # C++ class page: add the link right after the page title.
        link = "Python API: :py:class:`{}`".format(app.mrpt_cpp_to_py[docname])
        source[0] = re.sub(r"^(=+\n)", r"\1\n" + link + "\n", text, count=1, flags=re.MULTILINE)
        return
    if not docname.startswith(app.config.autoapi_root + "/"):
        return
    if "/_bindings" in docname:
        # Private modules: their classes are documented where the public
        # package imports them. Emptied to avoid duplicated targets.
        source[0] = ":orphan:\n"
        return
    # pybind11 enum docstrings list members one per line; escape a trailing
    # underscore (e.g. "None_"), which reST would read as a link:
    text = re.sub(r"^( +\w+)_$", r"\1\\_", text, flags=re.MULTILINE)
    m = re.search(r"^\.\. py:module:: (\S+)", text, re.MULTILINE)
    module = m.group(1) if m else ""

    def repl(cm):
        doc = app.mrpt_py_to_cpp.get("{}.{}".format(module, cm.group(2)))
        if not doc:
            return cm.group(0)
        # First line of the class body, after the directive options:
        return "{}\n{}   C++ API: :doc:`/{}`\n\n".format(cm.group(0), cm.group(1), doc)

    source[0] = re.sub(r"^( *)\.\. py:class:: (\w+)[^\n]*\n(?:\1   :[^\n]*\n)*", repl, text, flags=re.MULTILINE)


def setup(app):
    # Stubs must be in place before sphinx-autoapi reads them (builder-inited):
    app.connect("config-inited", collect_stubs)
    app.connect("config-inited", build_maps)
    app.connect("source-read", add_links)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
