"""
Python bindings for mrpt_rtti
"""
from __future__ import annotations
import typing
__all__: list[str] = ['CObject', 'TRuntimeClassId', 'classFactory', 'findRegisteredClass', 'getAllRegisteredClasses', 'getAllRegisteredClassesChildrenOf', 'registerAllPendingClasses', 'registerClass', 'registerClassCustomName']
class TRuntimeClassId:
    def createObject(self) -> typing.Any:  # unnamed C++ type
        ...
    @typing.overload
    def derivedFrom(self, arg0: TRuntimeClassId) -> bool:
        ...
    @typing.overload
    def derivedFrom(self, arg0: str) -> bool:
        ...
    def getBaseClass(self) -> TRuntimeClassId:
        ...
    @property
    def className(self) -> str:
        ...
class CObject:
    def GetRuntimeClass(self) -> TRuntimeClassId:
        ...
def classFactory(arg0: str) -> CObject:
    ...
def findRegisteredClass(arg0: str, arg1: bool) -> TRuntimeClassId:
    ...
def getAllRegisteredClasses() -> list[TRuntimeClassId]:
    ...
def getAllRegisteredClassesChildrenOf(arg0: TRuntimeClassId) -> list[TRuntimeClassId]:
    ...
def registerAllPendingClasses() -> None:
    ...
def registerClass(arg0: TRuntimeClassId) -> None:
    ...
def registerClassCustomName(arg0: str, arg1: TRuntimeClassId) -> None:
    ...
