"""
Python bindings for mrpt_math (with NumPy support)
"""
from __future__ import annotations
import mrpt.serialization
import numpy
import typing
__all__: list[str] = ['CHistogram', 'CMatrixDouble', 'CMatrixDouble22', 'CMatrixDouble33', 'CMatrixDouble44', 'CMatrixDouble66', 'CMatrixDouble77', 'CPolygon', 'CVectorDouble', 'CVectorFixedDouble2', 'CVectorFixedDouble3', 'CVectorFixedDouble6', 'TBoundingBox', 'TBoundingBoxf', 'TLine2D', 'TLine3D', 'TPlane', 'TPoint2D', 'TPoint2Df', 'TPoint3D', 'TPoint3Df', 'TPose2D', 'TPose3D', 'TPose3DQuat', 'TSegment2D', 'TSegment3D', 'TTwist2D', 'TTwist3D', 'wrapTo2Pi', 'wrapToPi']
class CMatrixDouble:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: int, arg1: int) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CVectorDouble:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: int) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray) -> None:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CMatrixDouble22:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CMatrixDouble33:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CMatrixDouble44:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CMatrixDouble66:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CMatrixDouble77:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CVectorFixedDouble2:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CVectorFixedDouble3:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class CVectorFixedDouble6:
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, array: numpy.ndarray) -> None:
        """
        Builds the matrix from a NumPy array of the same shape
        """
    def __repr__(self) -> str:
        ...
    def as_numpy(self) -> numpy.ndarray:
        ...
class TPoint2D:
    __hash__: typing.ClassVar[None] = None
    x: float
    y: float
    def __add__(self, arg0: TPoint2D) -> TPoint2D:
        ...
    def __array__(self, dtype = None, **kw):
        ...
    def __eq__(self, arg0: TPoint2D) -> bool:
        ...
    def __iadd__(self, arg0: TPoint2D) -> TPoint2D:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: list[float]) -> None:
        ...
    def __isub__(self, arg0: TPoint2D) -> TPoint2D:
        ...
    def __len__(self) -> int:
        ...
    def __mul__(self, arg0: float) -> TPoint2D:
        ...
    def __ne__(self, arg0: TPoint2D) -> bool:
        ...
    def __neg__(self) -> TPoint2D:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: TPoint2D) -> TPoint2D:
        ...
    def __truediv__(self, arg0: float) -> TPoint2D:
        ...
    def cast_float(self) -> typing.Any:  # unnamed C++ type
        ...
    def norm(self) -> float:
        ...
    def sqrNorm(self) -> float:
        ...
    def unitarize(self) -> TPoint2D:
        ...
class TPoint3D:
    __hash__: typing.ClassVar[None] = None
    x: float
    y: float
    z: float
    def __add__(self, arg0: TPoint3D) -> TPoint3D:
        ...
    def __array__(self, dtype = None, **kw):
        ...
    def __eq__(self, arg0: TPoint3D) -> bool:
        ...
    def __iadd__(self, arg0: TPoint3D) -> TPoint3D:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float, arg2: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: list[float]) -> None:
        ...
    def __isub__(self, arg0: TPoint3D) -> TPoint3D:
        ...
    def __len__(self) -> int:
        ...
    def __mul__(self, arg0: float) -> TPoint3D:
        ...
    def __ne__(self, arg0: TPoint3D) -> bool:
        ...
    def __neg__(self) -> TPoint3D:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: TPoint3D) -> TPoint3D:
        ...
    def __truediv__(self, arg0: float) -> TPoint3D:
        ...
    def cast_float(self) -> typing.Any:  # unnamed C++ type
        ...
    def cross(self, arg0: TPoint3D) -> TPoint3D:
        ...
    def dot(self, arg0: TPoint3D) -> float:
        ...
    def norm(self) -> float:
        ...
    def sqrNorm(self) -> float:
        ...
    def unitarize(self) -> TPoint3D:
        ...
class TPoint2Df:
    __hash__: typing.ClassVar[None] = None
    x: float
    y: float
    def __add__(self, arg0: TPoint2Df) -> TPoint2Df:
        ...
    def __array__(self, dtype: typing.Any = None, copy: typing.Any = None) -> numpy.ndarray:
        ...
    def __eq__(self, arg0: TPoint2Df) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: list[float]) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __ne__(self, arg0: TPoint2Df) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: TPoint2Df) -> TPoint2Df:
        ...
    def cast_double(self) -> TPoint2D:
        ...
    def norm(self) -> float:
        ...
    def sqrNorm(self) -> float:
        ...
    def unitarize(self) -> TPoint2Df:
        ...
class TPoint3Df:
    __hash__: typing.ClassVar[None] = None
    x: float
    y: float
    z: float
    def __add__(self, arg0: TPoint3Df) -> TPoint3Df:
        ...
    def __array__(self, dtype: typing.Any = None, copy: typing.Any = None) -> numpy.ndarray:
        ...
    def __eq__(self, arg0: TPoint3Df) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float, arg2: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: list[float]) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __ne__(self, arg0: TPoint3Df) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: TPoint3Df) -> TPoint3Df:
        ...
    def cast_double(self) -> TPoint3D:
        ...
    def cross(self, arg0: TPoint3Df) -> TPoint3Df:
        ...
    def dot(self, arg0: TPoint3Df) -> float:
        ...
    def norm(self) -> float:
        ...
    def sqrNorm(self) -> float:
        ...
    def unitarize(self) -> TPoint3Df:
        ...
class TPose2D:
    __hash__: typing.ClassVar[None] = None
    phi: float
    x: float
    y: float
    def __add__(self, arg0: TPose2D) -> TPose2D:
        ...
    def __array__(self, dtype = None, **kw):
        ...
    def __eq__(self, arg0: TPose2D) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float, arg2: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: list[float]) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __ne__(self, arg0: TPose2D) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def __sub__(self, arg0: TPose2D) -> TPose2D:
        ...
    def composePoint(self, arg0: TPoint2D) -> TPoint2D:
        ...
    def inverseComposePoint(self, arg0: TPoint2D) -> TPoint2D:
        ...
    def norm(self) -> float:
        ...
    def normalizePhi(self) -> None:
        ...
class TPose3D:
    __hash__: typing.ClassVar[None] = None
    pitch: float
    roll: float
    x: float
    y: float
    yaw: float
    z: float
    def __add__(self, arg0: TPose3D) -> TPose3D:
        ...
    def __array__(self, dtype = None, **kw):
        ...
    def __eq__(self, arg0: TPose3D) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: float, arg1: float, arg2: float, arg3: float, arg4: float, arg5: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: list[float]) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __ne__(self, arg0: TPose3D) -> bool:
        ...
    def __neg__(self) -> TPose3D:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def composePoint(self, arg0: TPoint3D) -> TPoint3D:
        ...
    def getHomogeneousMatrix(self) -> CMatrixDouble44:
        ...
    def getRotationMatrix(self) -> CMatrixDouble33:
        ...
    def inverseComposePoint(self, arg0: TPoint3D) -> TPoint3D:
        ...
    def norm(self) -> float:
        ...
class TSegment2D:
    point1: TPoint2D
    point2: TPoint2D
    @staticmethod
    def FromPoints(arg0: TPoint2D, arg1: TPoint2D) -> TSegment2D:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: TPoint2D, arg1: TPoint2D) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def contains(self, arg0: TPoint2D) -> bool:
        ...
    def distance(self, arg0: TPoint2D) -> float:
        ...
    def length(self) -> float:
        ...
class TSegment3D:
    point1: TPoint3D
    point2: TPoint3D
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: TPoint3D, arg1: TPoint3D) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def contains(self, arg0: TPoint3D) -> bool:
        ...
    def distance(self, arg0: TPoint3D) -> float:
        ...
    def length(self) -> float:
        ...
class TLine2D:
    coefs: list[float]
    @staticmethod
    def FromTwoPoints(arg0: TPoint2D, arg1: TPoint2D) -> TLine2D:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: TPoint2D, arg1: TPoint2D) -> None:
        ...
    @typing.overload
    def __init__(self, A: float, B: float, C: float) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def contains(self, arg0: TPoint2D) -> bool:
        ...
    def distance(self, arg0: TPoint2D) -> float:
        ...
    def evaluatePoint(self, arg0: TPoint2D) -> float:
        ...
    def unitarize(self) -> None:
        ...
class TLine3D:
    director: TPoint3D
    pBase: TPoint3D
    @staticmethod
    def FromTwoPoints(arg0: TPoint3D, arg1: TPoint3D) -> TLine3D:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: TPoint3D, arg1: TPoint3D) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def closestPointTo(self, arg0: TPoint3D) -> TPoint3D:
        ...
    def contains(self, arg0: TPoint3D) -> bool:
        ...
    def distance(self, arg0: TPoint3D) -> float:
        ...
    def unitarize(self) -> None:
        ...
class TPlane:
    coefs: list[float]
    @staticmethod
    def From3Points(arg0: TPoint3D, arg1: TPoint3D, arg2: TPoint3D) -> TPlane:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, A: float, B: float, C: float, D: float) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: TPoint3D, arg1: TPoint3D, arg2: TPoint3D) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def contains(self, arg0: TPoint3D) -> bool:
        ...
    def distance(self, arg0: TPoint3D) -> float:
        ...
    def evaluatePoint(self, arg0: TPoint3D) -> float:
        ...
    def unitarize(self) -> None:
        ...
class TBoundingBox:
    max: TPoint3D
    min: TPoint3D
    @staticmethod
    def PlusMinusInfinity() -> TBoundingBox:
        ...
    def __init__(self, arg0: TPoint3D, arg1: TPoint3D) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def containsPoint(self, arg0: TPoint3D) -> bool:
        ...
    def intersection(self, arg0: TBoundingBox) -> typing.Any:
        ...
    def unionWith(self, arg0: TBoundingBox) -> TBoundingBox:
        ...
    def volume(self) -> float:
        ...
class TBoundingBoxf:
    max: TPoint3Df
    min: TPoint3Df
    @staticmethod
    def PlusMinusInfinity() -> TBoundingBoxf:
        ...
    def __init__(self, arg0: TPoint3Df, arg1: TPoint3Df) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def containsPoint(self, arg0: TPoint3Df) -> bool:
        ...
    def unionWith(self, arg0: TBoundingBoxf) -> TBoundingBoxf:
        ...
    def volume(self) -> float:
        ...
class TTwist2D:
    omega: float
    vx: float
    vy: float
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, vx: float, vy: float, omega: float) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def asString(self) -> str:
        ...
    def rotate(self, arg0: float) -> None:
        ...
    def rotated(self, arg0: float) -> TTwist2D:
        ...
class TTwist3D:
    vx: float
    vy: float
    vz: float
    wx: float
    wy: float
    wz: float
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, vx: float, vy: float, vz: float, wx: float, wy: float, wz: float) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def asString(self) -> str:
        ...
    def rotate(self, arg0: TPose3D) -> None:
        ...
    def rotated(self, arg0: TPose3D) -> TTwist3D:
        ...
class TPose3DQuat:
    qr: float
    qx: float
    qy: float
    qz: float
    x: float
    y: float
    z: float
    def __array__(self, dtype = None, **kw):
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, x: float, y: float, z: float, qr: float, qx: float, qy: float, qz: float) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
class CPolygon(mrpt.serialization.CSerializable):
    def __init__(self) -> None:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def add_vertex(self, x: float, y: float) -> None:
        ...
    def get_vertex_x(self, arg0: int) -> float:
        ...
    def get_vertex_y(self, arg0: int) -> float:
        ...
    def get_vertices(self) -> tuple:
        """
        Returns (xs, ys) as two lists of vertex coordinates
        """
    def set_vertices(self, arg0: list[float], arg1: list[float]) -> None:
        ...
class CHistogram:
    def __init__(self, min: float, max: float, nBins: int) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def add(self, arg0: float) -> None:
        ...
    def clear(self) -> None:
        ...
    def getBinCount(self, arg0: int) -> int:
        ...
    def getBinRatio(self, arg0: int) -> float:
        ...
    def getHistogram(self) -> tuple:
        """
        Returns (bin_centers, hit_counts) as two lists
        """
    def getHistogramNormalized(self) -> tuple:
        """
        Returns (bin_centers, normalized_hits) — integral equals 1 as PDF
        """
def wrapTo2Pi(arg0: float) -> float:
    """
    Wrap angle to [0, 2*pi]
    """
def wrapToPi(arg0: float) -> float:
    """
    Wrap angle to [-pi, pi]
    """
