#include <ios>
#include <istream>
#include <iterator>
#include <locale>
#include <memory>
#include <mrpt/math/CMatrixDynamic.h>
#include <mrpt/math/CMatrixFixed.h>
#include <mrpt/math/CVectorDynamic.h>
#include <mrpt/math/MatrixVectorBase.h>
#include <mrpt/math/math_frwds.h>
#include <mrpt/math/matrix_size_t.h>
#include <optional>
#include <ostream>
#include <sstream> // __str__
#include <streambuf>
#include <string>

#include <functional>
#include <pybind11/pybind11.h>
#include <string>
#include <pybind11/stl.h>


#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>)
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*)
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>)
#endif

void bind_mrpt_math_MatrixVectorBase_2(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	{ // mrpt::math::MatrixVectorBase file:mrpt/math/MatrixVectorBase.h line:57
		pybind11::class_<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>, std::shared_ptr<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>>> cl(M("mrpt::math"), "MatrixVectorBase_float_mrpt_math_CMatrixFixed_float_4_4_t", "");
		cl.def( pybind11::init( [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>> const &o){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>(o); } ) );
		cl.def( pybind11::init( [](){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>(); } ) );
		cl.def("fill", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const float &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::fill, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::fill(const float &) --> void", pybind11::arg("val"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setConstant(const float) --> void", pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setConstant(size_t, size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setConstant(size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixFixed<float, 4, 4> (*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Constant(const float) --> class mrpt::math::CMatrixFixed<float, 4, 4>", pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixFixed<float, 4, 4> (*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Constant(size_t, size_t, const float) --> class mrpt::math::CMatrixFixed<float, 4, 4>", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("assign", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const unsigned long, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::assign, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::assign(const unsigned long, const float) --> void", pybind11::arg("N"), pybind11::arg("value"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setZero() --> void");
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setZero(size_t, size_t) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::setZero(size_t) --> void", pybind11::arg("nrows"));
		cl.def_static("Zero", (class mrpt::math::CMatrixFixed<float, 4, 4> (*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Zero() --> class mrpt::math::CMatrixFixed<float, 4, 4>");
		cl.def_static("Zero", (class mrpt::math::CMatrixFixed<float, 4, 4> (*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::Zero(size_t, size_t) --> class mrpt::math::CMatrixFixed<float, 4, 4>", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("coeffRef", (float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(int, int)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::coeffRef, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::coeffRef(int, int) --> float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("coeff", (const float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(int, int) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::coeff, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::coeff(int, int) const --> const float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("isSquare", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::isSquare, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::isSquare() const --> bool");
		cl.def("empty", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::empty, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::empty() const --> bool");
		cl.def("norm_inf", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::norm_inf, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::norm_inf() const --> float");
		cl.def("norm", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::norm, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::norm() const --> float");
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator+=(float) --> void", pybind11::arg("s"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator-=(float) --> void", pybind11::arg("s"));
		cl.def("__imul__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator*=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator*=(float) --> void", pybind11::arg("s"));
		cl.def("__add__", (class mrpt::math::CMatrixFixed<float, 4, 4> (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const class mrpt::math::CMatrixFixed<float, 4, 4> &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator+, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator+(const class mrpt::math::CMatrixFixed<float, 4, 4> &) const --> class mrpt::math::CMatrixFixed<float, 4, 4>", pybind11::arg("m2"));
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const class mrpt::math::CMatrixFixed<float, 4, 4> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator+=(const class mrpt::math::CMatrixFixed<float, 4, 4> &) --> void", pybind11::arg("m2"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const class mrpt::math::CMatrixFixed<float, 4, 4> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator-=(const class mrpt::math::CMatrixFixed<float, 4, 4> &) --> void", pybind11::arg("m2"));
		cl.def("sum", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::sum, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::sum() const --> float");
		cl.def("sum_abs", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::sum_abs, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::sum_abs() const --> float");
		cl.def("asString", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::asString, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::asString() const --> std::string");
		cl.def("inMatlabFormat", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>> const &o) -> std::string { return o.inMatlabFormat(); }, "");
		cl.def("inMatlabFormat", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const unsigned long) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::inMatlabFormat, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::inMatlabFormat(const unsigned long) const --> std::string", pybind11::arg("decimal_digits"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>> const &o, const std::string & a0) -> void { return o.saveToTextFile(a0); }, "", pybind11::arg("file"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1) -> void { return o.saveToTextFile(a0, a1); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1, bool const & a2) -> void { return o.saveToTextFile(a0, a1, a2); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"));
		cl.def("saveToTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::saveToTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::saveToTextFile(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const --> void", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"), pybind11::arg("userHeader"));
		cl.def("loadFromTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const std::string &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::loadFromTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::loadFromTextFile(const std::string &) --> void", pybind11::arg("file"));
		cl.def("assign", (class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 4> > & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>>::*)(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 4> > &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 4>>::operator=(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 4> > &) --> class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 4> > &", pybind11::return_value_policy::automatic, pybind11::arg(""));

		cl.def("__str__", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 4>> const &o) -> std::string { std::ostringstream s; using namespace mrpt::math; s << o; return s.str(); } );
	}
	{ // mrpt::math::MatrixVectorBase file:mrpt/math/MatrixVectorBase.h line:57
		pybind11::class_<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>, std::shared_ptr<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>>> cl(M("mrpt::math"), "MatrixVectorBase_float_mrpt_math_CMatrixDynamic_float_t", "");
		cl.def( pybind11::init( [](){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>(); } ) );
		cl.def( pybind11::init( [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>> const &o){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>(o); } ) );
		cl.def("fill", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const float &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::fill, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::fill(const float &) --> void", pybind11::arg("val"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setConstant(const float) --> void", pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setConstant(size_t, size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setConstant(size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixDynamic<float> (*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Constant(const float) --> class mrpt::math::CMatrixDynamic<float>", pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixDynamic<float> (*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Constant(size_t, size_t, const float) --> class mrpt::math::CMatrixDynamic<float>", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("assign", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const unsigned long, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::assign, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::assign(const unsigned long, const float) --> void", pybind11::arg("N"), pybind11::arg("value"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setZero() --> void");
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setZero(size_t, size_t) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::setZero(size_t) --> void", pybind11::arg("nrows"));
		cl.def_static("Zero", (class mrpt::math::CMatrixDynamic<float> (*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Zero() --> class mrpt::math::CMatrixDynamic<float>");
		cl.def_static("Zero", (class mrpt::math::CMatrixDynamic<float> (*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::Zero(size_t, size_t) --> class mrpt::math::CMatrixDynamic<float>", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("coeffRef", (float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(int, int)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::coeffRef, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::coeffRef(int, int) --> float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("coeff", (const float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(int, int) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::coeff, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::coeff(int, int) const --> const float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("isSquare", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::isSquare, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::isSquare() const --> bool");
		cl.def("empty", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::empty, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::empty() const --> bool");
		cl.def("norm_inf", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::norm_inf, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::norm_inf() const --> float");
		cl.def("norm", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::norm, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::norm() const --> float");
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator+=(float) --> void", pybind11::arg("s"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator-=(float) --> void", pybind11::arg("s"));
		cl.def("__imul__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator*=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator*=(float) --> void", pybind11::arg("s"));
		cl.def("__add__", (class mrpt::math::CMatrixDynamic<float> (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const class mrpt::math::CMatrixDynamic<float> &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator+, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator+(const class mrpt::math::CMatrixDynamic<float> &) const --> class mrpt::math::CMatrixDynamic<float>", pybind11::arg("m2"));
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const class mrpt::math::CMatrixDynamic<float> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator+=(const class mrpt::math::CMatrixDynamic<float> &) --> void", pybind11::arg("m2"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const class mrpt::math::CMatrixDynamic<float> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator-=(const class mrpt::math::CMatrixDynamic<float> &) --> void", pybind11::arg("m2"));
		cl.def("sum", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::sum, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::sum() const --> float");
		cl.def("sum_abs", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::sum_abs, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::sum_abs() const --> float");
		cl.def("asString", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::asString, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::asString() const --> std::string");
		cl.def("inMatlabFormat", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>> const &o) -> std::string { return o.inMatlabFormat(); }, "");
		cl.def("inMatlabFormat", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const unsigned long) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::inMatlabFormat, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::inMatlabFormat(const unsigned long) const --> std::string", pybind11::arg("decimal_digits"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>> const &o, const std::string & a0) -> void { return o.saveToTextFile(a0); }, "", pybind11::arg("file"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1) -> void { return o.saveToTextFile(a0, a1); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1, bool const & a2) -> void { return o.saveToTextFile(a0, a1, a2); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"));
		cl.def("saveToTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::saveToTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::saveToTextFile(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const --> void", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"), pybind11::arg("userHeader"));
		cl.def("loadFromTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const std::string &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::loadFromTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::loadFromTextFile(const std::string &) --> void", pybind11::arg("file"));
		cl.def("assign", (class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixDynamic<float> > & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>>::*)(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixDynamic<float> > &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixDynamic<float>>::operator=(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixDynamic<float> > &) --> class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixDynamic<float> > &", pybind11::return_value_policy::automatic, pybind11::arg(""));

		cl.def("__str__", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixDynamic<float>> const &o) -> std::string { std::ostringstream s; using namespace mrpt::math; s << o; return s.str(); } );
	}
}
