"""
Python bindings for mrpt::io — file and memory streams
"""
from __future__ import annotations
import mrpt.serialization
import typing
from . import zip
__all__: list[str] = ['APPEND', 'CCompressedInputStream', 'CCompressedOutputStream', 'CFileGZInputStream', 'CFileGZOutputStream', 'CFileInputStream', 'CFileOutputStream', 'CMemoryStream', 'CStream', 'CompressionOptions', 'CompressionType', 'OpenMode', 'SeekOrigin', 'TRUNCATE', 'archiveFrom', 'detect_compression', 'file_get_contents', 'loadBinaryFile', 'loadTextFile', 'sFromBeginning', 'sFromCurrent', 'sFromEnd', 'vectorToBinaryFile', 'zip']
class OpenMode:
    """
    Members:
    
      TRUNCATE
    
      APPEND
    """
    APPEND: typing.ClassVar[OpenMode]
    TRUNCATE: typing.ClassVar[OpenMode]
    __members__: typing.ClassVar[dict[str, OpenMode]]
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SeekOrigin:
    """
    Members:
    
      sFromBeginning
    
      sFromCurrent
    
      sFromEnd
    """
    __members__: typing.ClassVar[dict[str, SeekOrigin]]
    sFromBeginning: typing.ClassVar[SeekOrigin]
    sFromCurrent: typing.ClassVar[SeekOrigin]
    sFromEnd: typing.ClassVar[SeekOrigin]
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CStream:
    def Seek(self, offset: int, origin: SeekOrigin = ...) -> int:
        ...
    def getPosition(self) -> int:
        ...
    def getStreamDescription(self) -> str:
        ...
    def getTotalBytesCount(self) -> int:
        ...
    def getline(self, arg0: str) -> bool:
        ...
    def read(self, count: int) -> bytes:
        """
        Read up to `count` bytes from the stream, returns bytes object
        """
    def write(self, data: bytes) -> int:
        """
        Write bytes to the stream, returns number of bytes written
        """
class CFileInputStream(CStream):
    def __enter__(self) -> CFileInputStream:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, fileName: str) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def checkEOF(self) -> bool:
        ...
    def clearError(self) -> None:
        ...
    def close(self) -> None:
        ...
    def fileOpenCorrectly(self) -> bool:
        ...
    def getPosition(self) -> int:
        ...
    def getStreamDescription(self) -> str:
        ...
    def getTotalBytesCount(self) -> int:
        ...
    def is_open(self) -> bool:
        ...
    def open(self, fileName: str) -> bool:
        """
        Open a file for reading. Returns true on success.
        """
    def readLine(self, arg0: str) -> bool:
        ...
class CFileOutputStream(CStream):
    def __enter__(self) -> CFileOutputStream:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, fileName: str, mode: OpenMode = ...) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def close(self) -> None:
        ...
    def fileOpenCorrectly(self) -> bool:
        ...
    def getPosition(self) -> int:
        ...
    def getStreamDescription(self) -> str:
        ...
    def getTotalBytesCount(self) -> int:
        ...
    def is_open(self) -> bool:
        ...
    def open(self, fileName: str, mode: OpenMode = ...) -> bool:
        """
        Open a file for writing. Returns true on success.
        """
class CFileGZInputStream(CStream):
    def __enter__(self) -> CFileGZInputStream:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, fileName: str) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def checkEOF(self) -> bool:
        ...
    def close(self) -> None:
        ...
    def fileOpenCorrectly(self) -> bool:
        ...
    def filePathAtUse(self) -> str:
        ...
    def getPosition(self) -> int:
        ...
    def getStreamDescription(self) -> str:
        ...
    def getTotalBytesCount(self) -> int:
        ...
    def is_open(self) -> bool:
        ...
    def open(self, fileName: str) -> bool:
        """
        Open a .gz file for reading. Returns true on success.
        """
class CFileGZOutputStream(CStream):
    def __enter__(self) -> CFileGZOutputStream:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, fileName: str, mode: OpenMode = ..., compressionLevel: int = 1) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def close(self) -> None:
        ...
    def fileOpenCorrectly(self) -> bool:
        ...
    def filePathAtUse(self) -> str:
        ...
    def getPosition(self) -> int:
        ...
    def getStreamDescription(self) -> str:
        ...
    def is_open(self) -> bool:
        ...
    def open(self, fileName: str, compress_level: int = 1, mode: OpenMode = ...) -> bool:
        """
        Open a .gz file for writing. Returns true on success.
        """
class CMemoryStream(CStream):
    def Seek(self, offset: int, origin: SeekOrigin = ...) -> int:
        ...
    def __init__(self) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def clear(self) -> None:
        ...
    def getContents(self) -> bytes:
        """
        Return a copy of the stream buffer as a Python bytes object
        """
    def getPosition(self) -> int:
        ...
    def getTotalBytesCount(self) -> int:
        ...
    def loadBufferFromFile(self, arg0: str) -> bool:
        ...
    def saveBufferToFile(self, arg0: str) -> bool:
        ...
class CompressionType:
    """
    Members:
    
      None_
    
      Gzip
    
      Zstd
    """
    Gzip: typing.ClassVar[CompressionType]
    None_: typing.ClassVar[CompressionType]
    Zstd: typing.ClassVar[CompressionType]
    __members__: typing.ClassVar[dict[str, CompressionType]]
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class CompressionOptions:
    level: int
    type: CompressionType
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, type: CompressionType, level: int = 1) -> None:
        ...
    def __repr__(self) -> str:
        ...
class CCompressedInputStream(CStream):
    def __enter__(self) -> CCompressedInputStream:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, fileName: str) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def checkEOF(self) -> bool:
        ...
    def close(self) -> None:
        ...
    def fileOpenCorrectly(self) -> bool:
        ...
    def filePathAtUse(self) -> str:
        ...
    def getCompressionType(self) -> CompressionType:
        ...
    def getPosition(self) -> int:
        ...
    def getStreamDescription(self) -> str:
        ...
    def getTotalBytesCount(self) -> int:
        ...
    def is_open(self) -> bool:
        ...
    def open(self, fileName: str) -> bool:
        """
        Open a plain, gzip or zstd file for reading. Returns true on success.
        """
class CCompressedOutputStream(CStream):
    def __enter__(self) -> CCompressedOutputStream:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, fileName: str, mode: OpenMode = ..., options: CompressionOptions = ...) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def close(self) -> None:
        ...
    def fileOpenCorrectly(self) -> bool:
        ...
    def filePathAtUse(self) -> str:
        ...
    def getCompressionType(self) -> CompressionType:
        ...
    def getPosition(self) -> int:
        ...
    def getStreamDescription(self) -> str:
        ...
    def is_open(self) -> bool:
        ...
    def open(self, fileName: str, options: CompressionOptions = ..., mode: OpenMode = ...) -> bool:
        """
        Open a file for writing (default: zstd). Returns true on success.
        """
def archiveFrom(stream: CStream) -> mrpt.serialization.CArchive:
    """
    Returns a CArchive to read/write MRPT objects from/to the given stream. The stream is kept alive while the archive exists.
    """
def detect_compression(filePath: str) -> CompressionType:
    """
    Detects the compression of a file from its magic bytes (not its extension).
    """
def file_get_contents(fileName: str) -> str:
    """
    Load an entire text file as a single string. Raises on error.
    """
def loadBinaryFile(fileName: str) -> list[int] | None:
    """
    Load an entire binary file. Returns None (nullopt) on error, or a bytes-like list of uint8.
    """
def loadTextFile(fileName: str) -> list[str] | None:
    """
    Load a text file as a list of string lines. Returns None (nullopt) on error.
    """
def vectorToBinaryFile(data: bytes, fileName: str) -> bool:
    """
    Save a bytes object to a binary file. Returns False on error.
    """
APPEND: OpenMode
TRUNCATE: OpenMode
sFromBeginning: SeekOrigin
sFromCurrent: SeekOrigin
sFromEnd: SeekOrigin
