#include "src/mrpt/img/CCanvas.cpp"
#include "src/mrpt/img/CImage.cpp"
#include "src/mrpt/img/color_maps.cpp"
#include "src/mrpt/img/DistortionModel.cpp"
#include "src/mrpt/img/TCamera.cpp"
#include "src/mrpt/img/TColor.cpp"
#include "src/mrpt/img/TPixelCoord.cpp"
#include "src/mrpt/img/TStereoCamera.cpp"
