#include "src/mrpt/maps/CPointsMap_1.cpp"
#include "src/mrpt/maps/CPointsMap.cpp"
#include "src/mrpt/maps/CPointsMapXYZI.cpp"
#include "src/mrpt/maps/CRandomFieldGridMap2D.cpp"
#include "src/mrpt/maps/CRandomFieldGridMap3D.cpp"
#include "src/mrpt/maps/CReflectivityGridMap2D.cpp"
#include "src/mrpt/maps/CSimpleMap.cpp"
#include "src/mrpt/maps/CSimplePointsMap.cpp"
#include "src/mrpt/maps/CWeightedPointsMap.cpp"
#include "src/mrpt/maps/CWirelessPowerGridMap2D.cpp"
#include "src/mrpt/maps/metric_map_types.cpp"
#include "src/mrpt/maps/CVoxelMap.cpp"
#include "src/mrpt/maps/CVoxelMapBase.cpp"
#include "src/mrpt/maps/CVoxelMapOccupancyBase.cpp"
#include "src/mrpt/maps/CVoxelMapOccupancyBase_1.cpp"
#include "src/mrpt/maps/CVoxelMapOccupancyBase_2.cpp"

