#include <ios>
#include <istream>
#include <iterator>
#include <locale>
#include <memory>
#include <mrpt/math/CMatrixDynamic.h>
#include <mrpt/math/CMatrixFixed.h>
#include <mrpt/math/CVectorDynamic.h>
#include <mrpt/math/MatrixVectorBase.h>
#include <mrpt/math/math_frwds.h>
#include <mrpt/math/matrix_size_t.h>
#include <optional>
#include <ostream>
#include <sstream> // __str__
#include <streambuf>
#include <string>

#include <functional>
#include <pybind11/pybind11.h>
#include <string>
#include <stl_binders.hpp>


#ifndef BINDER_PYBIND11_TYPE_CASTER
	#define BINDER_PYBIND11_TYPE_CASTER
	PYBIND11_DECLARE_HOLDER_TYPE(T, std::shared_ptr<T>)
	PYBIND11_DECLARE_HOLDER_TYPE(T, T*)
	PYBIND11_MAKE_OPAQUE(std::shared_ptr<void>)
#endif

void bind_mrpt_math_MatrixVectorBase_2(std::function< pybind11::module &(std::string const &namespace_) > &M)
{
	{ // mrpt::math::MatrixVectorBase file:mrpt/math/MatrixVectorBase.h line:57
		pybind11::class_<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>, std::shared_ptr<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>>> cl(M("mrpt::math"), "MatrixVectorBase_float_mrpt_math_CMatrixFixed_float_3_1_t", "");
		cl.def( pybind11::init( [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>> const &o){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>(o); } ) );
		cl.def( pybind11::init( [](){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>(); } ) );
		cl.def("fill", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const float &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::fill, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::fill(const float &) --> void", pybind11::arg("val"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setConstant(const float) --> void", pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setConstant(size_t, size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setConstant(size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixFixed<float, 3, 1> (*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Constant(const float) --> class mrpt::math::CMatrixFixed<float, 3, 1>", pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixFixed<float, 3, 1> (*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Constant(size_t, size_t, const float) --> class mrpt::math::CMatrixFixed<float, 3, 1>", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("assign", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const unsigned long, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::assign, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::assign(const unsigned long, const float) --> void", pybind11::arg("N"), pybind11::arg("value"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setZero() --> void");
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setZero(size_t, size_t) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::setZero(size_t) --> void", pybind11::arg("nrows"));
		cl.def_static("Zero", (class mrpt::math::CMatrixFixed<float, 3, 1> (*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Zero() --> class mrpt::math::CMatrixFixed<float, 3, 1>");
		cl.def_static("Zero", (class mrpt::math::CMatrixFixed<float, 3, 1> (*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::Zero(size_t, size_t) --> class mrpt::math::CMatrixFixed<float, 3, 1>", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("coeffRef", (float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(int, int)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::coeffRef, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::coeffRef(int, int) --> float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("coeff", (const float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(int, int) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::coeff, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::coeff(int, int) const --> const float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("isSquare", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::isSquare, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::isSquare() const --> bool");
		cl.def("empty", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::empty, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::empty() const --> bool");
		cl.def("norm_inf", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::norm_inf, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::norm_inf() const --> float");
		cl.def("norm", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::norm, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::norm() const --> float");
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator+=(float) --> void", pybind11::arg("s"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator-=(float) --> void", pybind11::arg("s"));
		cl.def("__imul__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator*=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator*=(float) --> void", pybind11::arg("s"));
		cl.def("__add__", (class mrpt::math::CMatrixFixed<float, 3, 1> (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const class mrpt::math::CMatrixFixed<float, 3, 1> &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator+, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator+(const class mrpt::math::CMatrixFixed<float, 3, 1> &) const --> class mrpt::math::CMatrixFixed<float, 3, 1>", pybind11::arg("m2"));
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const class mrpt::math::CMatrixFixed<float, 3, 1> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator+=(const class mrpt::math::CMatrixFixed<float, 3, 1> &) --> void", pybind11::arg("m2"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const class mrpt::math::CMatrixFixed<float, 3, 1> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator-=(const class mrpt::math::CMatrixFixed<float, 3, 1> &) --> void", pybind11::arg("m2"));
		cl.def("sum", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::sum, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::sum() const --> float");
		cl.def("sum_abs", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::sum_abs, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::sum_abs() const --> float");
		cl.def("asString", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::asString, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::asString() const --> std::string");
		cl.def("inMatlabFormat", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>> const &o) -> std::string { return o.inMatlabFormat(); }, "");
		cl.def("inMatlabFormat", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const unsigned long) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::inMatlabFormat, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::inMatlabFormat(const unsigned long) const --> std::string", pybind11::arg("decimal_digits"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>> const &o, const std::string & a0) -> void { return o.saveToTextFile(a0); }, "", pybind11::arg("file"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1) -> void { return o.saveToTextFile(a0, a1); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1, bool const & a2) -> void { return o.saveToTextFile(a0, a1, a2); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"));
		cl.def("saveToTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::saveToTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::saveToTextFile(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const --> void", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"), pybind11::arg("userHeader"));
		cl.def("loadFromTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const std::string &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::loadFromTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::loadFromTextFile(const std::string &) --> void", pybind11::arg("file"));
		cl.def("assign", (class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 3, 1> > & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>>::*)(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 3, 1> > &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 3, 1>>::operator=(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 3, 1> > &) --> class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 3, 1> > &", pybind11::return_value_policy::automatic, pybind11::arg(""));

		cl.def("__str__", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 3, 1>> const &o) -> std::string { std::ostringstream s; using namespace mrpt::math; s << o; return s.str(); } );
	}
	{ // mrpt::math::MatrixVectorBase file:mrpt/math/MatrixVectorBase.h line:57
		pybind11::class_<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>, std::shared_ptr<mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>>> cl(M("mrpt::math"), "MatrixVectorBase_float_mrpt_math_CMatrixFixed_float_4_1_t", "");
		cl.def( pybind11::init( [](){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>(); } ) );
		cl.def( pybind11::init( [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>> const &o){ return new mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>(o); } ) );
		cl.def("fill", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const float &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::fill, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::fill(const float &) --> void", pybind11::arg("val"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setConstant(const float) --> void", pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setConstant(size_t, size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("setConstant", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setConstant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setConstant(size_t, const float) --> void", pybind11::arg("nrows"), pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixFixed<float, 4, 1> (*)(const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Constant(const float) --> class mrpt::math::CMatrixFixed<float, 4, 1>", pybind11::arg("value"));
		cl.def_static("Constant", (class mrpt::math::CMatrixFixed<float, 4, 1> (*)(size_t, size_t, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Constant, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Constant(size_t, size_t, const float) --> class mrpt::math::CMatrixFixed<float, 4, 1>", pybind11::arg("nrows"), pybind11::arg("ncols"), pybind11::arg("value"));
		cl.def("assign", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const unsigned long, const float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::assign, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::assign(const unsigned long, const float) --> void", pybind11::arg("N"), pybind11::arg("value"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setZero() --> void");
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setZero(size_t, size_t) --> void", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("setZero", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setZero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::setZero(size_t) --> void", pybind11::arg("nrows"));
		cl.def_static("Zero", (class mrpt::math::CMatrixFixed<float, 4, 1> (*)()) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Zero() --> class mrpt::math::CMatrixFixed<float, 4, 1>");
		cl.def_static("Zero", (class mrpt::math::CMatrixFixed<float, 4, 1> (*)(size_t, size_t)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Zero, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::Zero(size_t, size_t) --> class mrpt::math::CMatrixFixed<float, 4, 1>", pybind11::arg("nrows"), pybind11::arg("ncols"));
		cl.def("coeffRef", (float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(int, int)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::coeffRef, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::coeffRef(int, int) --> float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("coeff", (const float & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(int, int) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::coeff, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::coeff(int, int) const --> const float &", pybind11::return_value_policy::automatic, pybind11::arg("r"), pybind11::arg("c"));
		cl.def("isSquare", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::isSquare, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::isSquare() const --> bool");
		cl.def("empty", (bool (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::empty, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::empty() const --> bool");
		cl.def("norm_inf", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::norm_inf, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::norm_inf() const --> float");
		cl.def("norm", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::norm, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::norm() const --> float");
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator+=(float) --> void", pybind11::arg("s"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator-=(float) --> void", pybind11::arg("s"));
		cl.def("__imul__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(float)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator*=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator*=(float) --> void", pybind11::arg("s"));
		cl.def("__add__", (class mrpt::math::CMatrixFixed<float, 4, 1> (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const class mrpt::math::CMatrixFixed<float, 4, 1> &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator+, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator+(const class mrpt::math::CMatrixFixed<float, 4, 1> &) const --> class mrpt::math::CMatrixFixed<float, 4, 1>", pybind11::arg("m2"));
		cl.def("__iadd__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const class mrpt::math::CMatrixFixed<float, 4, 1> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator+=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator+=(const class mrpt::math::CMatrixFixed<float, 4, 1> &) --> void", pybind11::arg("m2"));
		cl.def("__isub__", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const class mrpt::math::CMatrixFixed<float, 4, 1> &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator-=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator-=(const class mrpt::math::CMatrixFixed<float, 4, 1> &) --> void", pybind11::arg("m2"));
		cl.def("sum", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::sum, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::sum() const --> float");
		cl.def("sum_abs", (float (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::sum_abs, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::sum_abs() const --> float");
		cl.def("asString", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)() const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::asString, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::asString() const --> std::string");
		cl.def("inMatlabFormat", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>> const &o) -> std::string { return o.inMatlabFormat(); }, "");
		cl.def("inMatlabFormat", (std::string (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const unsigned long) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::inMatlabFormat, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::inMatlabFormat(const unsigned long) const --> std::string", pybind11::arg("decimal_digits"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>> const &o, const std::string & a0) -> void { return o.saveToTextFile(a0); }, "", pybind11::arg("file"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1) -> void { return o.saveToTextFile(a0, a1); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"));
		cl.def("saveToTextFile", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>> const &o, const std::string & a0, enum mrpt::math::TMatrixTextFileFormat const & a1, bool const & a2) -> void { return o.saveToTextFile(a0, a1, a2); }, "", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"));
		cl.def("saveToTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::saveToTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::saveToTextFile(const std::string &, enum mrpt::math::TMatrixTextFileFormat, bool, const std::string &) const --> void", pybind11::arg("file"), pybind11::arg("fileFormat"), pybind11::arg("appendMRPTHeader"), pybind11::arg("userHeader"));
		cl.def("loadFromTextFile", (void (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const std::string &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::loadFromTextFile, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::loadFromTextFile(const std::string &) --> void", pybind11::arg("file"));
		cl.def("assign", (class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 1> > & (mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>>::*)(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 1> > &)) &mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator=, "C++: mrpt::math::MatrixVectorBase<float, mrpt::math::CMatrixFixed<float, 4, 1>>::operator=(const class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 1> > &) --> class mrpt::math::MatrixVectorBase<float, class mrpt::math::CMatrixFixed<float, 4, 1> > &", pybind11::return_value_policy::automatic, pybind11::arg(""));

		cl.def("__str__", [](mrpt::math::MatrixVectorBase<float,mrpt::math::CMatrixFixed<float, 4, 1>> const &o) -> std::string { std::ostringstream s; using namespace mrpt::math; s << o; return s.str(); } );
	}
}
