/*                    _
                     | |    Mobile Robot Programming Toolkit (MRPT)
 _ __ ___  _ __ _ __ | |_
| '_ ` _ \| '__| '_ \| __|          https://www.mrpt.org/
| | | | | | |  | |_) | |_
|_| |_| |_|_|  | .__/ \__|     https://github.com/MRPT/mrpt/
               | |
               |_|

 Copyright (c) 2005-2026, Individual contributors, see AUTHORS file
 See: https://www.mrpt.org/Authors - All rights reserved.
 SPDX-License-Identifier: BSD-3-Clause
*/

#include <gtest/gtest.h>
#include <mrpt/system/filesystem.h>
#include <mrpt/viz/CPointCloud.h>
#include <mrpt/viz/CPointCloudColoured.h>

using namespace mrpt::viz;

namespace
{
std::string tempPlyFile(const std::string& suffix)
{
  return mrpt::system::getTempFileName() + suffix + ".ply";
}
}  // namespace

TEST(PLY_import_export, PointCloudRoundTripAscii)
{
  CPointCloud pc;
  for (int i = 0; i < 20; i++)
  {
    pc.insertPoint(
        static_cast<float>(i), static_cast<float>(i) * 0.5f, static_cast<float>(i) * -0.25f);
  }

  const std::string file = tempPlyFile("_pc_ascii");
  const bool saveOk = pc.saveToPlyFile(file, false /*ascii*/);
  ASSERT_TRUE(saveOk) << pc.getSavePLYErrorString();

  CPointCloud pc2;
  const bool loadOk = pc2.loadFromPlyFile(file);
  ASSERT_TRUE(loadOk) << pc2.getLoadPLYErrorString();

  ASSERT_EQ(pc2.size(), pc.size());
  for (size_t i = 0; i < pc.size(); i++)
  {
    const auto& p1 = pc.getPoint3Df(i);
    const auto& p2 = pc2.getPoint3Df(i);
    EXPECT_NEAR(p1.x, p2.x, 1e-4f);
    EXPECT_NEAR(p1.y, p2.y, 1e-4f);
    EXPECT_NEAR(p1.z, p2.z, 1e-4f);
  }

  mrpt::system::deleteFile(file);
}

TEST(PLY_import_export, PointCloudRoundTripBinary)
{
  CPointCloud pc;
  for (int i = 0; i < 20; i++)
  {
    pc.insertPoint(
        static_cast<float>(i) * 0.1f, static_cast<float>(-i), static_cast<float>(i) * 2.0f);
  }

  const std::string file = tempPlyFile("_pc_bin");
  const bool saveOk = pc.saveToPlyFile(file, true /*binary*/);
  ASSERT_TRUE(saveOk) << pc.getSavePLYErrorString();

  CPointCloud pc2;
  const bool loadOk = pc2.loadFromPlyFile(file);
  ASSERT_TRUE(loadOk) << pc2.getLoadPLYErrorString();

  ASSERT_EQ(pc2.size(), pc.size());
  for (size_t i = 0; i < pc.size(); i++)
  {
    const auto& p1 = pc.getPoint3Df(i);
    const auto& p2 = pc2.getPoint3Df(i);
    EXPECT_NEAR(p1.x, p2.x, 1e-4f);
    EXPECT_NEAR(p1.y, p2.y, 1e-4f);
    EXPECT_NEAR(p1.z, p2.z, 1e-4f);
  }

  mrpt::system::deleteFile(file);
}

TEST(PLY_import_export, ColouredPointCloudRoundTrip)
{
  CPointCloudColoured pc;
  for (int i = 0; i < 15; i++)
  {
    mrpt::math::TPointXYZfRGBAu8 p(
        static_cast<float>(i), static_cast<float>(i) * -1.0f, 0.5f,
        static_cast<uint8_t>(i * 10 % 256), static_cast<uint8_t>(255 - i * 5), 128, 255);
    pc.insertPoint(p);
  }

  const std::string file = tempPlyFile("_pcc_ascii");
  const bool saveOk = pc.saveToPlyFile(file, false /*ascii*/);
  ASSERT_TRUE(saveOk) << pc.getSavePLYErrorString();

  CPointCloudColoured pc2;
  const bool loadOk = pc2.loadFromPlyFile(file);
  ASSERT_TRUE(loadOk) << pc2.getLoadPLYErrorString();

  ASSERT_EQ(pc2.size(), pc.size());
  for (size_t i = 0; i < pc.size(); i++)
  {
    const auto& p1 = pc.getPoint3Df(i);
    const auto& p2 = pc2.getPoint3Df(i);
    EXPECT_NEAR(p1.x, p2.x, 1e-4f);
    EXPECT_NEAR(p1.y, p2.y, 1e-4f);
    EXPECT_NEAR(p1.z, p2.z, 1e-4f);
  }

  mrpt::system::deleteFile(file);
}

TEST(PLY_import_export, SaveWithCommentsAndObjInfo)
{
  CPointCloud pc;
  pc.insertPoint(1.0f, 2.0f, 3.0f);

  const std::string file = tempPlyFile("_comments");
  std::vector<std::string> comments{"generated by an mrpt_viz unit test"};
  std::vector<std::string> objInfo{"unit test object"};
  const bool saveOk = pc.saveToPlyFile(file, false, comments, objInfo);
  ASSERT_TRUE(saveOk);

  CPointCloud pc2;
  std::vector<std::string> readComments;
  std::vector<std::string> readObjInfo;
  const bool loadOk = pc2.loadFromPlyFile(file, &readComments, &readObjInfo);
  ASSERT_TRUE(loadOk);
  EXPECT_EQ(pc2.size(), 1u);

  mrpt::system::deleteFile(file);
}

TEST(PLY_import_export, LoadNonExistentFileFails)
{
  CPointCloud pc;
  const bool loadOk = pc.loadFromPlyFile("/nonexistent/path/does_not_exist.ply");
  EXPECT_FALSE(loadOk);
  EXPECT_FALSE(pc.getLoadPLYErrorString().empty());
}

TEST(PLY_import_export, EmptyCloudRoundTrip)
{
  CPointCloud pc;
  const std::string file = tempPlyFile("_empty");
  const bool saveOk = pc.saveToPlyFile(file, false);
  ASSERT_TRUE(saveOk);

  CPointCloud pc2;
  const bool loadOk = pc2.loadFromPlyFile(file);
  ASSERT_TRUE(loadOk);
  EXPECT_EQ(pc2.size(), 0u);

  mrpt::system::deleteFile(file);
}
