name: CI macOS

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      COLCON_HOME: ${{ github.workspace }}/.colcon

    strategy:
      fail-fast: false
      matrix:
        name: [macos-latest-clang]
        build_type: [Release]
        include:
          - name: macos-latest-clang
            os: macos-latest
            compiler: clang

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git submodule
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Install Dependencies
        run: |
          brew install cmake ninja eigen assimp tinyxml2 zstd glfw
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Install colcon
        run: |
          pip3 install --break-system-packages colcon-common-extensions numpy

      - name: Colcon Build
        run: |
          colcon build \
            --event-handlers console_direct+ \
            --cmake-args \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DMRPT_BUILD_TESTING=ON \
              -DDISABLE_WXWIDGETS=ON \
              -DMRPT_WITH_QT=OFF

      - name: Colcon Test
        run: |
          colcon test \
            --event-handlers console_direct+ \
            --return-code-on-test-failure
